# Generated by Django 5.2.17 on 2026-08-08 23:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('name', models.CharField(max_length=180, verbose_name='الاسم')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('subject', models.CharField(max_length=180, verbose_name='الموضوع')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('status', models.CharField(choices=[('new', 'جديدة'), ('in_progress', 'قيد المتابعة'), ('replied', 'تم الرد'), ('closed', 'مغلقة')], db_index=True, default='new', max_length=20, verbose_name='الحالة')),
                ('admin_notes', models.TextField(blank=True, verbose_name='ملاحظات الفريق')),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='المتصفح')),
            ],
            options={
                'verbose_name': 'رسالة تواصل',
                'verbose_name_plural': 'رسائل التواصل',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='الرابط المختصر')),
                ('title', models.CharField(max_length=180, verbose_name='اسم الكورس')),
                ('category', models.CharField(choices=[('arabic', 'اللغة العربية'), ('quran', 'القرآن الكريم'), ('islamic', 'التربية الإسلامية')], db_index=True, max_length=20, verbose_name='التصنيف')),
                ('summary', models.CharField(max_length=320, verbose_name='الوصف المختصر')),
                ('description', models.TextField(verbose_name='الوصف الكامل')),
                ('age_group', models.CharField(max_length=100, verbose_name='الفئة العمرية')),
                ('level', models.CharField(max_length=100, verbose_name='المستوى')),
                ('duration', models.CharField(max_length=120, verbose_name='مدة البرنامج')),
                ('lesson_length', models.CharField(max_length=100, verbose_name='مدة الحصة')),
                ('goals', models.JSONField(default=list, verbose_name='أهداف الكورس')),
                ('outcomes', models.JSONField(default=list, verbose_name='النتائج المتوقعة')),
                ('accent', models.CharField(choices=[('mint', 'أخضر فاتح'), ('gold', 'ذهبي'), ('sky', 'سماوي'), ('rose', 'وردي هادئ'), ('lavender', 'بنفسجي هادئ'), ('emerald', 'زمردي')], default='mint', max_length=20, verbose_name='لون البطاقة')),
                ('is_featured', models.BooleanField(default=False, verbose_name='كورس مميز')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='ظاهر في الموقع')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب')),
            ],
            options={
                'verbose_name': 'كورس',
                'verbose_name_plural': 'الكورسات',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('question', models.CharField(max_length=300, verbose_name='السؤال')),
                ('answer', models.TextField(verbose_name='الإجابة')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='ظاهر في الموقع')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب')),
            ],
            options={
                'verbose_name': 'سؤال شائع',
                'verbose_name_plural': 'الأسئلة الشائعة',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('academy_name', models.CharField(default='أكاديمية آفاق', max_length=120, verbose_name='اسم الأكاديمية')),
                ('slogan', models.CharField(default='نرسّخ الهوية ونبني المستقبل', max_length=180, verbose_name='الشعار النصي')),
                ('email', models.EmailField(default='afaaqinstitute@gmail.com', max_length=254, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(default='+20 104 139 1631', max_length=40, verbose_name='رقم الهاتف')),
                ('whatsapp', models.CharField(default='201041391631', max_length=40, verbose_name='رقم واتساب الدولي')),
                ('contact_hours', models.CharField(default='يوميًا من 10 صباحًا حتى 10 مساءً بتوقيت القاهرة', max_length=220, verbose_name='أوقات التواصل')),
                ('facebook_url', models.URLField(blank=True, verbose_name='فيسبوك')),
                ('instagram_url', models.URLField(blank=True, verbose_name='إنستجرام')),
                ('youtube_url', models.URLField(blank=True, verbose_name='يوتيوب')),
            ],
            options={
                'verbose_name': 'إعدادات الموقع',
                'verbose_name_plural': 'إعدادات الموقع',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('quote', models.TextField(verbose_name='التقييم')),
                ('name', models.CharField(max_length=120, verbose_name='الاسم الظاهر')),
                ('location', models.CharField(blank=True, max_length=120, verbose_name='الدولة أو الوصف')),
                ('initials', models.CharField(blank=True, max_length=3, verbose_name='الحروف المختصرة')),
                ('rating', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='التقييم من 5')),
                ('is_approved', models.BooleanField(db_index=True, default=False, verbose_name='معتمد للنشر')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب')),
            ],
            options={
                'verbose_name': 'رأي عميل',
                'verbose_name_plural': 'آراء العملاء',
                'ordering': ('sort_order', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='TrialRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('subject', models.CharField(max_length=120, verbose_name='المادة')),
                ('course', models.CharField(blank=True, max_length=180, verbose_name='الكورس المطلوب')),
                ('student_name', models.CharField(max_length=180, verbose_name='اسم الطالب')),
                ('age', models.CharField(max_length=80, verbose_name='العمر')),
                ('level', models.CharField(max_length=120, verbose_name='المستوى')),
                ('preferred_day', models.CharField(max_length=80, verbose_name='اليوم المفضل')),
                ('preferred_period', models.CharField(max_length=80, verbose_name='الفترة المفضلة')),
                ('timezone', models.CharField(max_length=180, verbose_name='المنطقة الزمنية')),
                ('parent_name', models.CharField(max_length=180, verbose_name='اسم ولي الأمر')),
                ('whatsapp', models.CharField(max_length=50, verbose_name='واتساب')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('country', models.CharField(max_length=120, verbose_name='الدولة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('status', models.CharField(choices=[('new', 'جديد'), ('contacted', 'تم التواصل'), ('scheduled', 'تم تحديد الموعد'), ('completed', 'اكتملت الحصة'), ('cancelled', 'ملغي')], db_index=True, default='new', max_length=20, verbose_name='الحالة')),
                ('admin_notes', models.TextField(blank=True, verbose_name='ملاحظات الفريق')),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='المتصفح')),
            ],
            options={
                'verbose_name': 'طلب حصة تجريبية',
                'verbose_name_plural': 'طلبات الحصة التجريبية',
                'ordering': ('-created_at',),
            },
        ),
    ]
