# Generated by Django 5.2.17 on 2026-08-09 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_submission_idempotency'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='about_body_primary',
            field=models.TextField(default='نساعد الأطفال والطلاب العرب والمسلمين المقيمين خارج العالم العربي على الارتباط بلغتهم ودينهم، من خلال برامج أُعدت بعناية لتناسب العمر والمستوى وطبيعة التعلم أونلاين.', verbose_name='الفقرة الأولى في من نحن'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_body_secondary',
            field=models.TextField(default='نؤمن أن جودة التعليم تبدأ بفهم الطالب، وأن الثقة تُبنى عندما يرى ولي الأمر خطة واضحة وتقدمًا حقيقيًا واهتمامًا مستمرًا.', verbose_name='الفقرة الثانية في من نحن'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_heading_highlight',
            field=models.CharField(default='جسر إلى الهوية', max_length=180, verbose_name='العبارة المميزة في عنوان من نحن'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_heading_prefix',
            field=models.CharField(default='التعليم ليس معلومات فقط، بل', max_length=220, verbose_name='بداية عنوان من نحن'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_hero_description',
            field=models.TextField(default='أكاديمية تعليمية وُجدت لتقرب أبناءنا من لغتهم وقرآنهم وهويتهم، أينما كانت بيوتهم.', verbose_name='وصف واجهة من نحن'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cta_description',
            field=models.TextField(default='دعنا نتعرف إلى احتياجاته ونرشح له نقطة البداية الأنسب في حصة تجريبية مجانية.', verbose_name='وصف دعوة الحجز'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cta_eyebrow',
            field=models.CharField(default='خطوة صغيرة، أثر كبير', max_length=180, verbose_name='عبارة أعلى دعوة الحجز'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cta_title',
            field=models.CharField(default='ابدأ رحلة ابنك مع آفاق اليوم', max_length=220, verbose_name='عنوان دعوة الحجز'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_description',
            field=models.TextField(default='تعليم فردي مباشر للغة العربية والقرآن الكريم والتربية الإسلامية، يساعد أبناءنا على فهم لغتهم والاعتزاز بهويتهم.', verbose_name='وصف تذييل الموقع'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='goal_description',
            field=models.TextField(default='أن يخرج الطالب بمعرفة يستخدمها، وثقة تنمو، وعلاقة أجمل بلغته ودينه ومجتمعه.', verbose_name='نص الهدف'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='goal_title',
            field=models.CharField(default='أثر يبقى بعد انتهاء الحصة', max_length=220, verbose_name='عنوان الهدف'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_hero_description',
            field=models.TextField(default='تعليم العربية والقرآن والتربية الإسلامية بطريقة فردية تفاعلية تناسب أبناءنا في كل مكان، وتمنح الأسرة راحة وثقة في رحلة التعلّم.', verbose_name='وصف واجهة الرئيسية'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_hero_eyebrow',
            field=models.CharField(default='أكاديمية عربية لكل بيت', max_length=180, verbose_name='عبارة أعلى عنوان الرئيسية'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_hero_title_highlight',
            field=models.CharField(default='الهوية', max_length=120, verbose_name='الكلمة المميزة في عنوان الرئيسية'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_hero_title_prefix',
            field=models.CharField(default='نرسّخ', max_length=120, verbose_name='بداية عنوان الرئيسية'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_hero_title_suffix',
            field=models.CharField(default='ونبني المستقبل', max_length=180, verbose_name='نهاية عنوان الرئيسية'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mission_description',
            field=models.TextField(default='تقديم تجربة تعليمية مرنة وعالية الجودة تجمع العلم والتفاعل والمتابعة، وتراعي احتياج كل طالب.', verbose_name='نص الرسالة'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mission_title',
            field=models.CharField(default='تعليم فردي قريب من الطالب وحياته', max_length=220, verbose_name='عنوان الرسالة'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='vision_description',
            field=models.TextField(default='أن تكون آفاق شريكًا موثوقًا للأسر المسلمة في بناء صلة مستمرة بين أبنائها والعربية والقرآن والهوية.', verbose_name='نص الرؤية'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='vision_title',
            field=models.CharField(default='جيل يعتز بلغته ويعيش قيمه بوعي', max_length=220, verbose_name='عنوان الرؤية'),
        ),
    ]
