# Generated by Django 5.2.17 on 2026-08-09 21:20

import academy.models
import django.core.validators
from django.db import migrations, models


def set_official_facebook_when_blank(apps, schema_editor):
    site_settings = apps.get_model("academy", "SiteSettings")
    site_settings.objects.filter(facebook_url="").update(
        facebook_url="https://www.facebook.com/profile.php?id=61592705708385"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0003_sitesettings_about_body_primary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('name', models.CharField(max_length=140, unique=True, verbose_name='اسم الخطة')),
                ('description', models.TextField(blank=True, verbose_name='وصف الخطة')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='السعر')),
                ('currency', models.CharField(help_text='مثال: دولار أو USD', max_length=30, verbose_name='العملة')),
                ('billing_period', models.CharField(help_text='مثال: شهريًا أو لكل 8 حصص', max_length=80, verbose_name='فترة السعر')),
                ('lesson_count', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='عدد الحصص')),
                ('lesson_duration', models.CharField(blank=True, max_length=80, verbose_name='مدة الحصة')),
                ('features', models.JSONField(default=list, help_text='أدخل قائمة JSON مثل: ["حصص فردية", "متابعة دورية"]', validators=[academy.models.validate_feature_list], verbose_name='مميزات الخطة')),
                ('cta_label', models.CharField(default='احجز الآن', max_length=80, verbose_name='نص زر الحجز')),
                ('is_featured', models.BooleanField(default=False, verbose_name='الخطة المميزة')),
                ('is_active', models.BooleanField(db_index=True, default=False, verbose_name='ظاهرة في الموقع')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب')),
            ],
            options={
                'verbose_name': 'خطة سعر',
                'verbose_name_plural': 'الخطط والأسعار',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='facebook_url',
            field=models.URLField(blank=True, default='https://www.facebook.com/profile.php?id=61592705708385', verbose_name='فيسبوك'),
        ),
        migrations.RunPython(set_official_facebook_when_blank, migrations.RunPython.noop),
    ]
